import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  formData: {
    OPBillRecepitLine: [
      {
        ServiceID: "",
        Unit: 0,
        Rate: 0,
        DiscType: "",
        Discount: 0,
        Amount: 0,
        PriorityType: "",
        Remarks: "",
      },
    ],
    OPReceipt_Payment_Line: [
      {
        PayMode: "T",
        Amount: 0,
        RefNo: "REF",
      },
    ],
    PatientTitle: "",
    SalutationName: "",
    PatientName: "",
    DOB: "",
    Gender: "",
    MaritalStatus: "",
    IDtype: "",
    IDNo: "",
    Nationality: "",
    Language: "",
    Occupation: "",
    MobileNo: "",
    EmailId: "",
    Address: "",
    StateCode: "",
    CityCode: "",
    CountryCode: "",
    Pincode: "",
    BirthCountry: "",
    PassportNo: "",
    VISANo: "",
    VISAType: 0,
    VISAValidity: "",
    FormCstatus: "",
    Mob_CountryCode: "",
    AltMob_CountryCode: "",
    AltMobileNo: "",
    CurrAddress: "",
    PermAddress: "",
    Area: "",
    Pat_Is_symptoms: 0,
    Pat_Is_historyoffever: 0,
    Pat_Is_outofcountry1month: 0,
    Pat_Is_diseaseoutbreak: 0,
    Pat_Is_healthcareworker: 0,
    Pat_Is_disease_last1month: 0,
    Pat_Is_chickenpox: 0,
    Pat_Is_measles: 0,
    Pat_Is_mumps: 0,
    Pat_Is_rubella: 0,
    Pat_Is_diarrheasymptoms: 0,
    Pat_Is_activeTB: 0,
    Pat_Is_receivewhatsapp: 0,
    RelationType: "",
    RelationName: "",
    RelationMobileno: "",
    UserID: "",
    annualincome: 0,
    prefferedLanguages: 0,
    religion: 0,
    kin_Address: "",
    kin_StateCode: 1,
    kin_CityCode: 1,
    kin_CountryCode: 0,
    kin_Pincode: "",
    kin_Area: "",
    OccRemark: "",
    BloodGroup: 0,
    docId: 0,
    appointmentId: 0,
    RefSource: 13,
    VistType: 3,
    PatientType: "",
    PayorID: 0,
    Remarks: "",
    InternalDocId: 0,
    ExternalDocId: 0,
    GrossAmount: 0,
    DiscountAmount: 0,
    GLAmount: 0,
    PatientResponsibility: 0,
    NetAmount: 0,
    APPStartDate: "",
    Package: "",
    AppRemarks: "",
    AppRefSource: "",
  },
};

export const saveOPModuleSlice = createSlice({
  name: "SaveOPModule",
  initialState,
  reducers: {
    opBillReceipt: (state, action) => {},
  },
});

const { opBillReceipt } = saveOPModuleSlice.actions;

export default saveOPModuleSlice.reducer;
